// <auto-generated />
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20230530184759_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Entities.Contributor", b =>
                {
                    b.Property<string>("RncIdentificationCard")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RncIdentificationCard");

                    b.ToTable("Contributors");

                    b.HasData(
                        new
                        {
                            RncIdentificationCard = "98754321012",
                            Active = true,
                            Name = "JUAN PEREZ",
                            Type = "PERSONA FISICA"
                        },
                        new
                        {
                            RncIdentificationCard = "123456789",
                            Active = false,
                            Name = "FARMACIA TU SALUD",
                            Type = "PERSONA JURIDICA"
                        });
                });

            modelBuilder.Entity("Api.Entities.TaxReceipt", b =>
                {
                    b.Property<string>("NCF")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Itbis18")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RncIdentificationCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NCF");

                    b.ToTable("TaxReceipts");

                    b.HasData(
                        new
                        {
                            NCF = "E310000000001",
                            Amount = 200.00m,
                            Itbis18 = 36.00m,
                            RncIdentificationCard = "98754321012"
                        },
                        new
                        {
                            NCF = "E310000000002",
                            Amount = 1000.00m,
                            Itbis18 = 180.00m,
                            RncIdentificationCard = "98754321012"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
